# Generated by Django 4.1.3 on 2023-05-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_item_item_category_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expense',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
