# Generated by Django 4.1.3 on 2023-05-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_item_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_ordered',
            field=models.DateTimeField(),
        ),
    ]
