# Generated by Django 4.1.3 on 2023-06-15 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0007_sale_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='storeOwner',
        ),
        migrations.AddField(
            model_name='store',
            name='storeOwner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='store_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
