# Generated by Django 4.2.2 on 2023-06-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_item_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
