# Generated by Django 4.1.5 on 2023-06-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expense',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
