# Generated by Django 4.1.5 on 2023-06-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_item_expense_alter_item_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
