# Generated by Django 4.1.5 on 2023-06-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_sale_amount_alter_sale_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
