# Generated by Django 4.1.4 on 2023-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_alter_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_ordered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
