# Generated by Django 4.1.7 on 2023-07-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_alter_item_date_ordered_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_ordered',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
